version: "3.3"
services:
  web:
    build: .
    ports:
      - 83:80
    networks:
      - lcom
    volumes:
      - ./app:/app
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ctt_server"
      - "traefik.frontend.rule=Host:ctt-ui.loicroux.com"

networks:
  lcom:
    external: true
