name: Tests

on: [pull_request]

jobs:
  build:
    env:
      CI: true

    runs-on: ubuntu-16.04

    steps:
      - name: Get yarn cache directory path
        id: cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/checkout@v2

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      # - uses: borales/actions-yarn@v2.0.0
      #   with:
      #     cmd: tests
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
